#! /usr/bin/perl
require "getopt.pl";
do Getopt('TAaULDltdpgiensv');



$target = $opt_T;
$applname = $opt_A ? $opt_A : "";
$appldir = $opt_a ? $opt_a : "";
$applobjs = $opt_U ? $opt_U : "";
$kernel_lib = $opt_L ? $opt_L : "";
$kernel_funcobjs = $opt_f ? "true" : "";
$srclang = $opt_l ? $opt_l : "c";
$templatedir = $opt_t ? $opt_t : "asp_sample";
$dbgenv = $opt_d ? "TOPPERS_".$opt_d : "";
$enable_trace = $opt_r ? "true" : "";
$net_if = $opt_i;
$net_dev = $opt_v;
$net_proto = $opt_n;
$trans_proto = $opt_s;
$aspsampledir = "sample";

#
#  オブジェクトファイル名の拡張子を返す
#
sub get_objext {
	local(@uname);

	use POSIX;
	@uname = do uname();
	if ($uname[0] =~ /^cygwin/i) {
		return("exe");
	}
	else {
		return("");
	}
}

#
#  プログラムの場所を検索する
#
sub get_path {
	local($progname, @pathlist) = @_;
	local($path);

	foreach $path (@pathlist) {
		if (-x $path."/".$progname) {
			return($path."/".$progname);
		}
	}
	return("");
}

#
#  Makefile を変換する
#
sub convMakefileSub {
	local($infile, $outfile) = @_;
	local($line, $varname, $varval);

	unless (open(INFILE, $infile)) {
		print STDERR "tinet_asp_configure: can't open $infile\n";
		exit(1);
	}
	unless (open(OUTFILE, ">> ".$outfile)) {
		print STDERR "tinet_asp_configure: can't open $outfile\n";
		exit(1);
	}

	while ($line = <INFILE>) {
		chop $line;
		while ($line =~ /^(.*)\@\(([A-Za-z0-9_]+)\)(.*)$/) {
			$line = $1.$vartable{$2}.$3;
		}
		print OUTFILE $line,"\n";
	}

	close(INFILE);
	close(OUTFILE);
}

#
#  Makefile を変換する
#
sub convMakefile {
	local($infile, $copyright, $outfile) = @_;
	local($aspMakefile);

	# Mekfile 有ればリネームする。
	print STDERR "tinet_asp_configure: Generating $outfile from $infile.\n";
	if (-f $outfile) {
		print STDERR "tinet_asp_configure: $outfile exists.",
						"  Save as $outfile.bak.\n";
		rename($outfile, $outfile.".bak");
	}

	# TINET のコピーライトを書き込む
	&convMakefileSub($copyright, $outfile);

	# 出力する Makefile をオープンする
	unless (open(OUTFILE, ">> ".$outfile)) {
		print STDERR "tinet_asp_configure: can't open $outfile\n";
		exit(1);
	}

	# 参照する sample/Makefile をオープンする。
	$aspMakefile = $aspsampledir."/Makefile";
	unless (open(ASPFILE, $aspMakefile)) {
		print STDERR "tinet_asp_configure: can't open $aspMakefile\n";
		exit(1);
	}

	# 参照する sample/Makefile のコピーライトを読み飛ばす。
	while ($line = <ASPFILE>) {
		chop $line;
		if ($line !~ /^#/) {
			print OUTFILE $line,"\n";
			last;
		}
	}

	# 'APPLNAME = @(APPLNAME)' の行まで書き込む
	while ($line = <ASPFILE>) {
		chop $line;
		while ($line =~ /^(.*)\@\(([A-Za-z0-9_]+)\)(.*)$/) {
			$line = $1.$vartable{$2}.$3;
		}
		print OUTFILE $line,"\n";
		if ($line =~ /^APPLNAME = /) {
			last;
		}
	}

	# '#' 前の行まで書き込む
	while ($line = <ASPFILE>) {
		chop $line;
		while ($line =~ /^(.*)\@\(([A-Za-z0-9_]+)\)(.*)$/) {
			$line = $1.$vartable{$2}.$3;
		}
		if ($line =~ /^#/) {
			last;
		}
		print OUTFILE $line,"\n";
	}

	# 一度出力する Makefile をクローズする。
	close(OUTFILE);

	# TINET の Makefile を書き込む
	&convMakefileSub($infile, $outfile);

	# もう一度出力する Makefile をオープンする
	unless (open(OUTFILE, ">> ".$outfile)) {
		print STDERR "tinet_asp_configure: can't open $outfile\n";
		exit(1);
	}

	# 参照する sample/Makefile の最終行まで書き込む
	while ($line = <ASPFILE>) {
		chop $line;
		while ($line =~ /^(.*)\@\(([A-Za-z0-9_]+)\)(.*)$/) {
			$line = $1.$vartable{$2}.$3;
		}
		print OUTFILE $line,"\n";
	}

	close(OUTFILE);
	close(ASPFILE);
}

#
#  Makefile を生成する
#
sub genMakefile {
	local($file, $mandatory) = @_;
	local($path, $copyright);

	$path = $sampledir.$file.".".$applname;
	$copyright = $sampledir.$file.".copyright";
	if (-f $path) {
		&convMakefile($path, $copyright, $file);
		return;
	}	

	$path = $sampledir.$file;
	if ($mandatory || -f $path) {
		&convMakefile($path, $copyright, $file);
	}	
}

#
#  ファイルを変換する
#
sub convert {
	local($infile, $outfile) = @_;
	local($line, $varname, $varval);

	print STDERR "tinet_asp_configure: Generating $outfile from $infile.\n";
	if (-f $outfile) {
		print STDERR "tinet_asp_configure: $outfile exists.",
						"  Save as $outfile.bak.\n";
		rename($outfile, $outfile.".bak");
	}
	unless (open(INFILE, $infile)) {
		print STDERR "tinet_asp_configure: can't open $infile\n";
		exit(1);
	}
	unless (open(OUTFILE, "> ".$outfile)) {
		print STDERR "tinet_asp_configure: can't open $outfile\n";
		exit(1);
	}

	while ($line = <INFILE>) {
		chop $line;
		while ($line =~ /^(.*)\@\(([A-Za-z0-9_]+)\)(.*)$/) {
			$line = $1.$vartable{$2}.$3;
		}
		print OUTFILE $line,"\n";
	}

	close(INFILE);
	close(OUTFILE);
}

#
#  サンプルを見つけてファイルを生成する
#
sub generate {
	local($file, $mandatory) = @_;
	local($path);

	$path = $sampledir.$file.".".$applname;
	if (-f $path) {
		do convert($path, $file);
		return;
	}	

	$path = $sampledir.$file;
	if ($mandatory || -f $path) {
		do convert($path, $file);
	}	
}

#
#  TINET のソースディレクトリ名を取り出す
#
$pwd = `pwd`; chop $pwd;
if ($opt_e) {
	$tinetabsdir = $tinetdir = $opt_e;
}
elsif ($0 =~ /(.*)\/tinet_asp_configure/) {
	$tinetdir = $1;
	if ($tinetdir =~ /^\//) {
		$tinetabsdir = $tinetdir;
	}
	else {
		$tinetabsdir = $pwd."/".$tinetdir;
	}
}
else {
	$tinetabsdir = $tinetdir = $pwd;
}
$sampledir = $tinetdir."/".$templatedir."/";

#
#  ソースディレクトリ名を取り出す
#
$pwd = `pwd`; chop $pwd;
if ($opt_D) {
	$srcabsdir = $srcdir = $opt_D;
}
elsif ($0 =~ /(.*)\/tinet\/tinet_asp_configure/) {
	$srcdir = $1;
	if ($srcdir =~ /^\//) {
		$srcabsdir = $srcdir;
	}
	else {
		$srcabsdir = $pwd."/".$srcdir;
	}
}
else {
	$srcabsdir = $srcdir = $pwd;
}
$aspsampledir = $srcdir."/".$aspsampledir;

$perl = $opt_p ? $opt_p : do get_path("perl", ("/usr/local/bin", "/usr/bin"));
$cfg = $opt_g ? $opt_g : "\$(SRCDIR)/cfg/cfg/cfg";
$cfgfile = $opt_g ? $opt_g : $srcdir."/cfg/cfg/cfg";

#
#  オプションの確認
#
unless ($opt_T) {
	print STDERR "tinet_asp_configure: -T option is mandatory\n";
	print STDERR "Installed targets are:\n";
	foreach $targetname (<$srcdir/target/[a-zA-Z1-9]*>) {
		$targetname =~ s|$srcdir/target/||;
		print STDERR "\t$targetname\n";
	}
	exit(1);
}
unless ($opt_i) {
	print STDERR "tinet_jsp_configure: -i option is mandatory\n";
	exit(1);
}
else {
	unless ($opt_v) {
		print STDERR "tinet_jsp_configure: -v option is mandatory\n";
		exit(1);
	}
}
if ($opt_n) {
	unless ($opt_n eq "inet4" || $opt_n eq "inet6") {
		print STDERR "tinet_jsp_configure: inet4 or inet6 expected in -n option\n";
		exit(1);
	}
}
else {
	print STDERR "tinet_jsp_configure: -n option is mandatory\n";
	exit(1);
}
if ($opt_s) {
	unless ($opt_s eq "tcp" || $opt_s eq "udp" || $opt_s eq "tcp/udp") {
		print STDERR "tinet_jsp_configure: tcp, udp or tcp/udp expected in -s option\n";
		exit(1);
	}
}
else {
	print STDERR "tinet_jsp_configure: -s option is mandatory\n";
	exit(1);
}

#
#  変数テーブルの作成
#
%vartable = ();
$vartable{"TARGET"} = $target;
$vartable{"APPLNAME"} = $applname;
$vartable{"APPLDIR"} = $appldir;
$vartable{"APPLOBJS"} = $applobjs;
$vartable{"KERNEL_LIB"} = $kernel_lib;
$vartable{"KERNEL_FUNCOBJS"} = $kernel_funcobjs;
$vartable{"SRCDIR"} = $srcdir;
$vartable{"SRCABSDIR"} = $srcabsdir;
$vartable{"SRCLANG"} = $srclang;
$vartable{"DBGENV"} = $dbgenv;
$vartable{"ENABLE_TRACE"} = $enable_trace;
$vartable{"PERL"} = $perl;
$vartable{"CFG"} = $cfg;
$objext = do get_objext();
$vartable{"OBJEXT"} = $objext;
$vartable{"TINETDIR"} = $tinetdir;
$vartable{"TINETABSDIR"} = $tinetabsdir;
$vartable{"NET_IF"} = $net_if;
$vartable{"NET_DEV"} = $net_dev;

#
#  -n オプションの処理
#

$vartable{"SUPPORT_INET4"} = "#SUPPORT_INET4 = true";
$vartable{"SUPPORT_INET6"} = "#SUPPORT_INET6 = true";
if ($net_proto eq "inet4") {
	$vartable{"SUPPORT_INET4"} = "SUPPORT_INET4 = true";
}
if ($net_proto eq "inet6") {
	$vartable{"SUPPORT_INET6"} = "SUPPORT_INET6 = true";
}

#
#  -s オプションの処理
#

$vartable{"SUPPORT_TCP"} = "#SUPPORT_TCP = true";
$vartable{"SUPPORT_UDP"} = "#SUPPORT_UDP = true";
if ($trans_proto eq "tcp" || $trans_proto eq "tcp/udp") {
	$vartable{"SUPPORT_TCP"} = "SUPPORT_TCP = true";
}
if ($trans_proto eq "udp" || $trans_proto eq "tcp/udp") {
	$vartable{"SUPPORT_UDP"} = "SUPPORT_UDP = true";
}

#
#  ターゲットディレクトリのチェック
#

if (! -d $srcdir."/target/".$target) {
	print STDERR "tinet_asp_configure: $srcdir/target/$target not exist\n";
	exit(1);
}

#
#  Makefile とアプリケーションファイルの生成
#

&genMakefile("Makefile", 1);
do generate($applname.".c", 0);
do generate($applname.".cpp", 0);
do generate($applname.".h", 0);
do generate($applname.".cfg", 0);
do generate("tinet_".$applname.".cfg", 0);
do generate("route_cfg.c", 0);
do generate("tinet_app_config.h", 0);

#
#  cfg ができているかのチェック
#

if (!(-x ($objext == "" ? $cfgfile : $cfgfile.".".$objext))) {
	print STDERR "Please compile the configurator (cfg).\n";
}
